[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ddlpdfparser"
version = "0.0.1"
dependencies = [
    "PyMuPDF",
    "Pillow",
    "pandas",
    "numpy",
    "scikit-learn"
]